apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: "ci-cd-infra"
  description: "Recursos de infraestrutura para a aplicação ci-cd"
  links:
    - title: Repositório de Código
      url: "https://github.com/romagalhaes/ci-cd"
  annotations:
    backstage.io/techdocs-ref: dir:.
    backstage.io/source-location: url:https://github.com/romagalhaes/ci-cd-infra
    github.com/project-slug: romagalhaes/ci-cd-infra
    idp.mycompany.com/repository-role: infrastructure
spec:
  type: infrastructure
  owner: "group:default/guests"
  lifecycle: production